dnl This file generated by the ROSE build script.
AC_DEFUN([ROSE_OPTIONAL_PROJECTS],[
OPTIONAL_PROJECTS=
AC_SUBST(OPTIONAL_PROJECTS)


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/BinaryAnalysisTools/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/BinaryAnalysisTools])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS BinaryAnalysisTools"

dnl List of all makefiles for this project							-*- autoconf -*-
AC_CONFIG_FILES(projects/BinaryAnalysisTools/Makefile)

dnl The bROwSE tool depends on Wt (web toolkit)
AC_ARG_WITH(wt,
	[  --with-wt=PATH   Installation prefix for optional Wt (web toolkit) library.],
	[AC_DEFINE(ROSE_USE_WT, 1, [Defined if the web toolkit Wt is available.])
	 if test "$with_wt" = "yes"; then WT_PREFIX=/usr; else WT_PREFIX="$with_wt"; fi],
	[with_wt=no])
AC_SUBST(WT_PREFIX)
AM_CONDITIONAL(ROSE_USE_WT, test "$with_wt" != "no")


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/CodeProperties/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/CodeProperties])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS CodeProperties"

dnl List of all makefiles for this project							-*- autoconf -*-
AC_CONFIG_FILES([projects/CodeProperties/Makefile])

dnl Even if this project is present in ROSE's "projects" directory, we might not have the prerequisites to compile
dnl this project.  Enable the project's makefiles by using the ROSE_ENABLE_projectname automake conditional.
dnl Many prerequisites have probably already been tested by ROSE's main configure script, so we don't need to list
dnl them here again (although it usually doesn't hurt).
AC_MSG_CHECKING([whether CodeProperties project prerequisites are satisfied])
AC_MSG_RESULT([yes])
rose_enable_project_code_properties=yes

AM_CONDITIONAL([ROSE_ENABLE_PROJECT_CODE_PROPERTIES], [test "$rose_enable_project_code_properties" = yes])


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/CodeThorn/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/CodeThorn])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS CodeThorn"

dnl List of all makefiles for this project						-*- autoconf -*-
AC_CONFIG_FILES([projects/CodeThorn/Makefile
		projects/CodeThorn/src/Makefile])

AC_MSG_CHECKING([whether CodeThorn project prerequisites are satisfied])
AC_MSG_RESULT([yes])
rose_enable_project_CodeThorn=yes

AM_CONDITIONAL([ROSE_ENABLE_PROJECT_CODETHORN], [test "$rose_enable_project_CodeThorn" = yes])


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/MatrixTesting/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/MatrixTesting])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS MatrixTesting"

dnl List of all makefiles for this project							-*- autoconf -*-
AC_CONFIG_FILES(projects/MatrixTesting/Makefile)

dnl The matrix query tool depends on Wt (web toolkit)
AC_ARG_WITH(wt,
	[  --with-wt=PATH   Installation prefix for optional Wt (web toolkit) library.],
	[AC_DEFINE(ROSE_USE_WT, 1, [Defined if the web toolkit Wt is available.])
	 if test "$with_wt" = "yes"; then WT_PREFIX=/usr; else WT_PREFIX="$with_wt"; fi],
	[with_wt=no])
AC_SUBST(WT_PREFIX)
AM_CONDITIONAL(ROSE_USE_WT, test "$with_wt" != "no")


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/simulator2/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/simulator2])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS simulator2"

dnl List of all makefiles for this project							-*- autoconf -*-
AC_CONFIG_FILES(projects/simulator2/Makefile)


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/SnippetTools/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/SnippetTools])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS SnippetTools"

dnl List of all makefiles for this project							-*- autoconf -*-
AC_CONFIG_FILES(projects/SnippetTools/Makefile)


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/TALCDataLayout/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/TALCDataLayout])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS TALCDataLayout"

dnl List of all makefiles for this project						-*- autoconf -*-
AC_CONFIG_FILES([projects/TALCDataLayout/Makefile
		projects/TALCDataLayout/src/Makefile
		projects/TALCDataLayout/src/haopt/Makefile
		projects/TALCDataLayout/src/main/Makefile
		projects/TALCDataLayout/src/meta/Makefile
		projects/TALCDataLayout/src/modules/Makefile
		projects/TALCDataLayout/src/runtime/Makefile
		projects/TALCDataLayout/src/utilities/Makefile
		projects/TALCDataLayout/tests/Makefile])

dnl Even if this project is present in ROSE's "projects" directory, we might not have the prerequisites to compile
dnl this project.  Enable the project's makefiles by using the ROSE_ENABLE_projectname automake conditional.
dnl Many prerequisites have probably already been tested by ROSE's main configure script, so we don't need to list
dnl them here again (although it usually doesn't hurt).
AC_MSG_CHECKING([whether TALCDataLayout project prerequisites are satisfied])
AC_MSG_RESULT([yes])
rose_enable_project_talcdatalayout=yes

AM_CONDITIONAL([ROSE_ENABLE_PROJECT_TALCDATALAYOUT], [test "$rose_enable_project_talcdatalayout" = yes])


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/traceAnalysis/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/traceAnalysis])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS traceAnalysis"

dnl List of all makefiles for this project						-*- autoconf -*-
AC_CONFIG_FILES([projects/traceAnalysis/Makefile])

dnl Even if this project is present in ROSE's "projects" directory, we might not have the prerequisites to compile
dnl this project.  Enable the project's makefiles by using the ROSE_ENABLE_projectname automake conditional.
dnl Many prerequisites have probably already been tested by ROSE's main configure script, so we don't need to list
dnl them here again (although it usually doesn't hurt).
AC_MSG_CHECKING([whether traceAnalysis project prerequisites are satisfied])
AC_MSG_RESULT([yes])
rose_enable_project_trace_analysis=yes

AM_CONDITIONAL([ROSE_ENABLE_PROJECT_TRACE_ANALYSIS], [test "$rose_enable_project_trace_analysis" = yes])
])
